### ISSUE TITLE
AND・OR検索

### ISSUE THREAD

**Issue by Javakky** [Javakky/NicoApiClient#7]
AND 検索、 OR 検索を実装したい。
OR は両端にしか対応していなさそうなので、OR メソッドを読んだら終了、AND メソッドは任意の回数繰り返し呼べるが、中で Optional な OR 要素を指定できるとよさそう。

**Comment by yashiroyrahs** [comment]
設計案

strが渡されたとき、シングル検索
keyword = "VOCALOID"
→q=VOCALOID

List[str]が渡されたとき、リストの中の文字列についてOR検索
keyword = ["初音ミク", "鏡音リン", "GUMI"]
→q=初音ミク OR 鏡音リンOR GUMI

List[List[str]]が渡されたとき、リストのリストについてAND検索、リストのリストの文字列についてOR検索
keyword = [["初音ミク", "鏡音リン", "GUMI"], ["歌ってみた", "踊ってみた", "MMD"], ["VOCALOID"]]
→q=初音ミク OR 鏡音リン OR GUMI 歌ってみた OR 踊ってみた OR MMD VOCALOID

**Comment by Javakky** [comment]
なるほど！
僕としてはメソッドチェーンで

```python
query(["初音ミク", "鏡音リン"]).and(["歌ってみた", "踊ってみた"]).and("VOCALOID")
```

という形式を想定していたのですが、配列で渡す形式とどちらがよさそうかご意見伺いたいです。
こちらの強みとしては、配列のネストが1段より深くならないため、コードの見晴らしが良くなる点と、 `and` でつながっていることがはっきりとする点だと考えています。

**Comment by yashiroyrahs** [comment]
「Python .and()」と検索しても使い方が出てこなかったり、挙動を見るためにコードを書いたらエラーを吐いてしまうのでよくわからないのですが、これはどのような動きをするコードなのでしょうか(keywordには何が渡される)？

**Comment by Javakky** [comment]
このような書き方で

> q=初音ミク OR 鏡音リン 歌ってみた OR 踊ってみた VOCALOID

を表現できるような実装をしてはどうか、という話です。

**Comment by yashiroyrahs** [comment]
なるほど自作メソッドでしたか。
メソッドチェーンのほうがわかりやすいのでそちらの実装でやってみます。
